// _TO_CONVERT_NOW/0example-react-longstanding/Pages/Welcome.tsx
import { Link } from '@inertiajs/react';
import React from 'react';
import useRoute from '@/Hooks/useRoute';
import useTypedPage from '@/Hooks/useTypedPage';
import { Head } from '@inertiajs/react';

interface Props {
  canLogin: boolean;
  canRegister: boolean;
  laravelVersion: string;
  phpVersion: string;
}

export default function Welcome({ canLogin, canRegister, laravelVersion, phpVersion }: Props) {
  return (
    <>
      <div className="relative sm:flex sm:justify-center sm:items-center min-h-screen bg-dots-darker bg-center bg-gray-100 dark:bg-dots-lighter dark:bg-gray-900 selection:bg-red-500 selection:text-white">
        {canLogin ? (
          <div className="sm:fixed sm:top-0 sm:right-0 p-6 text-right">
            {page.props.auth.user ? (
              <Link
                href={route('dashboard')}
                className="font-semibold text-gray-600 hover:text-gray-900 dark:text-gray-400 dark:hover:text-white focus:outline focus:outline-2 focus:rounded-sm focus:outline-red-500"
              >
                Dashboard
              </Link>
            ) : (
              <>
                <Link
                  href={route('login')}
                  className="font-semibold text-gray-600 hover:text-gray-900 dark:text-gray-400 dark:hover:text-white focus:outline focus:outline-2 focus:rounded-sm focus:outline-red-500"
                >
                  Log in
                </Link>

                {canRegister ? (
                  <Link
                    href={route('register')}
                    className="ml-4 font-semibold text-gray-600 hover:text-gray-900 dark:text-gray-400 dark:hover:text-white focus:outline focus:outline-2 focus:rounded-sm focus:outline-red-500"
                  >
                    Register
                  </Link>
                ) : null}
              </>
            )}
          </div>
        ) : null}
        Laravel v{laravelVersion} (PHP v{phpVersion})
      </div>
    </>
  );
}

// resources/js/Pages/Welcome.vue
<script lang="ts" setup>
import {Head, Link} from '@inertiajs/vue3';
import Rating from "primevue/rating";

defineProps({
  canLogin: {
    type: Boolean,
  },
  canRegister: {
    type: Boolean,
  },
  laravelVersion: {
    type: String,
    required: true,
  },
  phpVersion: {
    type: String,
    required: true,
  },
});

</script>

<template>
  <Head title="Knowii - Welcome"/>
  <div class="bg-gray-50 text-black/50">
    <header class="">
      <nav v-if="canLogin" class="-mx-3 flex flex-1 justify-end">
        <Link
          v-if="$page.props.auth.user"
          :href="route('dashboard')"
          class=""
        >
          Dashboard
        </Link>

        <template v-else>
          <Link
            :href="route('login')"
            class=""
          >
            Log in
          </Link>

          <Link
            v-if="canRegister"
            :href="route('register')"
            class=""
          >
            Register
          </Link>
        </template>
      </nav>
    </header>

    <main class="mt-6">
      Content
      <Rating></Rating>
    </main>

    <footer class="">
      Footer
    </footer>
  </div>
</template>
